# Generated by Django 3.1.5 on 2021-01-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=64)),
                ('merchant_id', models.CharField(max_length=16, unique=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('address', models.TextField()),
                ('review_count', models.IntegerField()),
                ('zip_code', models.IntegerField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('rating', models.FloatField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.merchant', verbose_name='node to merchant')),
            ],
        ),
    ]
