# Generated by Django 3.1.5 on 2021-01-29 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210129_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_scrapped',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 13, 19, 57, 270626)),
        ),
    ]
