# Generated by Django 3.1.5 on 2021-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_elements',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_scrapped',
            field=models.DateField(blank=True, null=True),
        ),
    ]
