# Generated by Django 3.1.5 on 2021-02-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20210203_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_url',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_url',
            field=models.CharField(blank=True, default='url', max_length=256, null=True),
        ),
    ]
